### PR TITLE
Also rename num and squeeze to qnum, qsqueeze

### PR DESCRIPTION
**Pull request by tkelman**
since your fallback would otherwise be for `function $f(args...; kws...)` - looks like this is in line with what you're doing for identity and position?

### CODE REVIEW

**Comment by goropikari** [comment]
According to [qutip document](http://qutip.org/docs/4.1/installation.html), qutip needs numpy, scipy, cython, nose, and matplotlib. So I will add some codes to install above dependency.

**Comment by tkelman** [comment]
seems like the conda package should mark those dependencies though?

**Comment by goropikari** [comment]
Sorry, I delete my comment by mistake.

repost
> According to [qutip document](http://qutip.org/docs/4.1/installation.html), qutip need numpy, scipy, cython, nose, and matplotlib. So I will add some codes to install above dependency.

When I don't specify dependency packages, I fail to install qutip. But I specify those packages, qutip installation succeeds.

**Comment by tkelman** [comment]
that seems like a packaging mistake, shouldn't the conda package manager handle installation of dependencies?

**Comment by goropikari** [comment]
Since qutip minimally requires numpy, scipy, and cython, those three packages are automatically installed by conda package manager.
In the past it seems matplotlib and nose are also installed, but now the two packages are not mandatory.

**Comment by goropikari** [comment]
About renamed fn, I mistook the argument. Funtions 'num' and 'position' also have keyword arguments. 
And when I fixed arithmetic operators and functions return type, I forgot to fix operators_class functions. To prevent my forgetting, I will define all function in QuTiP.jl file.

**Pull request merged**
